# Generated by Django 5.2.1 on 2025-05-16 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_remove_course_price_remove_course_stripe_price_id_and_more"),
        ("users", "0004_remove_payment_payment_method_payment_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма (в центах)"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Stripe Session ID"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создано"),
                    ("paid", "Оплачено"),
                    ("unpaid", "Не оплачено"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменено"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Stripe Price ID"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Stripe Product ID"),
        ),
    ]
