# Generated by Django 5.2.1 on 2025-05-16 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price_course_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
        migrations.RemoveField(
            model_name="course",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="course",
            name="stripe_product_id",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
