name: CI/CD Pipeline

on:
  push:
    branches:
      - feature_8_docker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          sudo apt update && \
          sudo apt install -y docker.io docker-compose

      - name: Build and Test
        run: |
          cd lms_project
          docker-compose build
          docker-compose up -d db redis
          sleep 10
          docker-compose exec web python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/lms_project || exit
            git stash || true
            git fetch origin
            git checkout feature_8_docker
            git pull origin feature_8_docker

            docker compose down
            docker compose up -d --build

            docker compose exec web python manage.py migrate --noinput
            docker compose exec web python manage.py collectstatic --noinput